### ISSUE TITLE
SQL logic error no such table: logs

### ISSUE THREAD

**Issue by yoandydt** [saleem-mirza/serilog-sinks-sqlite#15]
If LoggerConfiguration SQLite is created with parameters retentionPeriod and retentionCheckInterval the application gives an access error to the tableName because it starts a timer that you are going to try to clean data to a table that has not yet been created.

**Comment by yoandydt** [comment]
In the class SQLiteSink.cs call InitializeDatabase (); before ... if (retentionPeriod.HasValue) {... and not later. I have done it and correct the error.

**Comment by SeppPenner** [comment]
@saleem-mirza I gues you can close this as the PR is merged already?
