### ISSUE TITLE
Add rolling file functionality

### ISSUE THREAD

**Issue by mika76** [saleem-mirza/serilog-sinks-sqlite#17]
Basically allow for a new db to be created daily like https://github.com/serilog/serilog-sinks-rollingfile

This would help a lot because the log files would then not get huge and people could just email them when needed - and if the same limits were included as RollingFile then there would never be more than 31 files logged.

**Comment by saleem-mirza** [comment]
Hi @mika76. I have rolled out a new version . please check https://www.nuget.org/packages/Serilog.Sinks.SQLite/5.0.0-dev-00086 and let me know if it works for you.

**Comment by mika76** [comment]
Thanks will check it out
