### ISSUE TITLE
Update Newtonsoft.Json nuget package.

### ISSUE THREAD

**Issue by SeppPenner** [saleem-mirza/serilog-sinks-sqlite#20]
https://github.com/saleem-mirza/serilog-sinks-sqlite/blob/dev/src/Serilog.Sinks.SQLite/Serilog.Sinks.SQLite.csproj --> 

|Package|Link|Installed Version|Latest Version|
|-|-|-|-|
|Newtonsoft.Json|https://www.nuget.org/packages/Newtonsoft.Json/|12.0.1|12.0.2|

**Comment by SeppPenner** [comment]
PR is there: https://github.com/saleem-mirza/serilog-sinks-sqlite/pull/21.

**Comment by saleem-mirza** [comment]
Please explain what issue this PR solves or what value it brings?

**Comment by SeppPenner** [comment]
I thought the benefits of keeping dependencies up to date are clear:

* Fixes security issues
* Bugfixes
* New features (Possibly)

The release changes are here: https://github.com/JamesNK/Newtonsoft.Json/releases

**Comment by SeppPenner** [comment]
Ok, if you want to provide software that doesn't use the latest features and security patches^^ Not understandable for me though.

**Comment by saleem-mirza** [comment]
I don't just jump into what's new but stability. Thanks for your contribution though.

**Comment by SeppPenner** [comment]
> I don't just jump into what's new but stability. Thanks for your contribution though.

I disagree with that statement but it's your project.
