### ISSUE TITLE
How to use custom columns in Serilog.Sinks.SQLite

### ISSUE THREAD

**Issue by AtlantisDe** [saleem-mirza/serilog-sinks-sqlite#30]
### Description
How to use custom columns in Serilog.Sinks.SQLite

### default

```sql
CREATE TABLE Logs (
    id              INTEGER      PRIMARY KEY AUTOINCREMENT,
    Timestamp       TEXT,
    Level           VARCHAR (10),
    Exception       TEXT,
    RenderedMessage TEXT,
    Properties      TEXT
);

```

### i need like Entity insert 
```c#
Logger.Information(  new UserItem {  Name="customer",Age=99999} );
```
```sql
CREATE TABLE LogsEntityDemo  (
    id              INTEGER      PRIMARY KEY AUTOINCREMENT,
    Name           VARCHAR (10),
    Age  INT,
);

```
```c#
        /// <summary>UserItem</summary>
        public class UserItem
        {
            /// <summary>Name</summary>
            public string Name { get; set; }
            /// <summary>Age</summary>
            public int Age { get; set; }
        }
```

### pls help me 
 
```html
tks very much
```

**Comment by Davidos533** [comment]
Hello, it's simple
Tiny extension library - Serilog.Sinks.SQLite just not support custom db table
My solution just dowload library, and rewrite app parts for you purposes 

I hust download Serilog.Sinks.SQLite from: https://github.com/saleem-mirza/serilog-sinks-sqlite
-next i extract project files
-create new C# net core 3.1 classes library project in my solution
-put in my new project downloaded Serilog.Sinks.SQLite .cs files
-dowload required nu get packeges
 
My library project config:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Serilog" Version="2.11.0" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.115.5" />
  </ItemGroup>

</Project>`
