### ISSUE TITLE
No Nuget Package for .net 4.5.1

### ISSUE THREAD

**Issue by on3al** [saleem-mirza/serilog-sinks-sqlite#6]
It looks there is nothing that would prevent this working with .net 4.5.1? Would you update the nuget package to offer a 4.5.1 compatible project?

**Comment by saleem-mirza** [comment]
Sure, will look into over weekend.

**Comment by saleem-mirza** [comment]
@on3al, thanks for suggestion. I have updated nugget package with support of multiple .net frameworks. Cheers!
