### ISSUE TITLE
Null Reference exception thrown from CreateLogger

### ISSUE THREAD

**Issue by rtompot** [saleem-mirza/serilog-sinks-sqlite#7]
Using Visual Studio 2015. To reproduce, create a new Cross-Platform Xamarin.Forms app. Install the latest Serilog nuget in the Portable, Android projects. Installl the latest Serilog-Sinks-SQLite nuget (3.8.3) into the Android project. Add the following logic to the MainActivity.cs file in the Android project, in the OnCreate method:

var logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.SQLite(@"APSApp.db", "Logs")
                .CreateLogger(); //NullReferenceException thrown from this statement

PCL Profile is .NET Framework 4.5.1, Windows 8.1, Xamarin.Android, Xamarin.iOS, Xamarin.iOS (Classic), Xamarin.Mac

**Comment by saleem-mirza** [comment]
@rtompot, Sorry for trouble. Unfortunately, I don't have access to Xamarin so can't speak about it. However I have tested and confirm this sink work perfectly fine with .net 4.5.1 and above .

**Comment by rtompot** [comment]
Xamarin is freely available with Visual Studio
